// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArH3MyuQQrJFkflDUoKPmnPrcbGBJve_E',
    appId: '1:827808614853:web:bd9f7a93807088e33ee3ac',
    messagingSenderId: '827808614853',
    projectId: 'flavorfusion-74d39',
    authDomain: 'flavorfusion-74d39.firebaseapp.com',
    storageBucket: 'flavorfusion-74d39.appspot.com',
    measurementId: 'G-5MVCBCR4L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrwrpjeZ867GENIn-N_zJaPegBrufbZmI',
    appId: '1:827808614853:android:e1be907c0d9584873ee3ac',
    messagingSenderId: '827808614853',
    projectId: 'flavorfusion-74d39',
    storageBucket: 'flavorfusion-74d39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLoQcvWsepMzTV--w1Ia-VVZBiBrkSwM',
    appId: '1:827808614853:ios:813695e5f8e8212e3ee3ac',
    messagingSenderId: '827808614853',
    projectId: 'flavorfusion-74d39',
    storageBucket: 'flavorfusion-74d39.appspot.com',
    iosBundleId: 'com.example.flavorfusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLoQcvWsepMzTV--w1Ia-VVZBiBrkSwM',
    appId: '1:827808614853:ios:9c31cad41da6ee073ee3ac',
    messagingSenderId: '827808614853',
    projectId: 'flavorfusion-74d39',
    storageBucket: 'flavorfusion-74d39.appspot.com',
    iosBundleId: 'com.example.flavorfusion.RunnerTests',
  );
}
